### ISSUE TITLE
怎么没有提供数据啊

### ISSUE THREAD

**Issue by AIR-hl** [andreeaiana/simplifying_nnr#1]

**Comment by andreeaiana** [comment]
We use the publicly available MIND dataset (see https://msnews.github.io/). The data is automatically downloaded and pre-processed when running the [train.py](https://github.com/andreeaiana/simplifying_nnr/blob/main/src/train.py)  script. Alternatively, you can manually download the chosen datasets in the [data](https://github.com/andreeaiana/simplifying_nnr/tree/main/data/) directory using the URLs in the [MIND data config](https://github.com/andreeaiana/simplifying_nnr/blob/main/configs/datamodule/mind.yaml). 

I now updated the README with more details about the datasets.
